// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationsByCategory = `-- name: CountApplicationsByCategory :many
SELECT COALESCE(NULLIF(category, ''), 'Uncategorized')::text AS category, COUNT(*)::bigint AS total
FROM applications
WHERE user_id = $1
GROUP BY COALESCE(NULLIF(category, ''), 'Uncategorized')::text
ORDER BY category
`

type CountApplicationsByCategoryRow struct {
	Category string
	Total    int64
}

func (q *Queries) CountApplicationsByCategory(ctx context.Context, userID pgtype.UUID) ([]CountApplicationsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsByCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountApplicationsByCategoryRow
	for rows.Next() {
		var i CountApplicationsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countApplicationsBySavedMonth = `-- name: CountApplicationsBySavedMonth :many
SELECT to_char(date_trunc('month', created_at), 'YYYY-MM') AS month, COUNT(*)::bigint AS total
FROM applications
WHERE user_id = $1
GROUP BY date_trunc('month', created_at)
ORDER BY date_trunc('month', created_at)
`

type CountApplicationsBySavedMonthRow struct {
	Month string
	Total int64
}

func (q *Queries) CountApplicationsBySavedMonth(ctx context.Context, userID pgtype.UUID) ([]CountApplicationsBySavedMonthRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsBySavedMonth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountApplicationsBySavedMonthRow
	for rows.Next() {
		var i CountApplicationsBySavedMonthRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countApplicationsBySource = `-- name: CountApplicationsBySource :many
SELECT source, COUNT(*)::bigint AS total
FROM applications
WHERE user_id = $1
GROUP BY source
ORDER BY source
`

type CountApplicationsBySourceRow struct {
	Source string
	Total  int64
}

func (q *Queries) CountApplicationsBySource(ctx context.Context, userID pgtype.UUID) ([]CountApplicationsBySourceRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsBySource, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountApplicationsBySourceRow
	for rows.Next() {
		var i CountApplicationsBySourceRow
		if err := rows.Scan(&i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countApplicationsByStatus = `-- name: CountApplicationsByStatus :many
SELECT status, COUNT(*)::bigint AS total
FROM applications
WHERE user_id = $1
GROUP BY status
ORDER BY status
`

type CountApplicationsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountApplicationsByStatus(ctx context.Context, userID pgtype.UUID) ([]CountApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountApplicationsByStatusRow
	for rows.Next() {
		var i CountApplicationsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countApplicationsByUser = `-- name: CountApplicationsByUser :one
SELECT COUNT(*)::bigint AS total
FROM applications
WHERE user_id = $1
`

func (q *Queries) CountApplicationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
