// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    user_id,
    source,
    external_id,
    title,
    company_name,
    category,
    job_type,
    candidate_required_location,
    salary_text,
    external_url,
    publication_date,
    description,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, user_id, source, external_id, title, company_name, category,
          job_type, candidate_required_location, salary_text, external_url,
          publication_date, description, status, created_at, updated_at
`

type CreateApplicationParams struct {
	UserID                    pgtype.UUID
	Source                    string
	ExternalID                string
	Title                     string
	CompanyName               string
	Category                  string
	JobType                   string
	CandidateRequiredLocation string
	SalaryText                string
	ExternalUrl               string
	PublicationDate           pgtype.Timestamptz
	Description               string
	Status                    string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.CompanyName,
		arg.Category,
		arg.JobType,
		arg.CandidateRequiredLocation,
		arg.SalaryText,
		arg.ExternalUrl,
		arg.PublicationDate,
		arg.Description,
		arg.Status,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.CompanyName,
		&i.Category,
		&i.JobType,
		&i.CandidateRequiredLocation,
		&i.SalaryText,
		&i.ExternalUrl,
		&i.PublicationDate,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
