// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_notes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationNote = `-- name: CreateApplicationNote :one
INSERT INTO application_notes (
    application_id,
    user_id,
    body
)
SELECT
    a.id,
    a.user_id,
    $1::text
FROM applications a
WHERE a.id = $2::uuid
  AND a.user_id = $3::uuid
RETURNING id, application_id, user_id, body, created_at
`

type CreateApplicationNoteParams struct {
	Body          string
	ApplicationID pgtype.UUID
	UserID        pgtype.UUID
}

func (q *Queries) CreateApplicationNote(ctx context.Context, arg CreateApplicationNoteParams) (ApplicationNote, error) {
	row := q.db.QueryRow(ctx, createApplicationNote, arg.Body, arg.ApplicationID, arg.UserID)
	var i ApplicationNote
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApplicationNote = `-- name: DeleteApplicationNote :one
DELETE FROM application_notes
WHERE id = $1
  AND user_id = $2
RETURNING id
`

type DeleteApplicationNoteParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteApplicationNote(ctx context.Context, arg DeleteApplicationNoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteApplicationNote, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getApplicationNotes = `-- name: GetApplicationNotes :many
SELECT n.id, n.application_id, n.user_id, n.body, n.created_at
FROM application_notes n
JOIN applications a ON a.id = n.application_id
WHERE n.application_id = $1
  AND n.user_id = $2
  AND a.user_id = $2
ORDER BY n.created_at DESC
`

type GetApplicationNotesParams struct {
	ApplicationID pgtype.UUID
	UserID        pgtype.UUID
}

func (q *Queries) GetApplicationNotes(ctx context.Context, arg GetApplicationNotesParams) ([]ApplicationNote, error) {
	rows, err := q.db.Query(ctx, getApplicationNotes, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationNote
	for rows.Next() {
		var i ApplicationNote
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
