// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID                        pgtype.UUID
	UserID                    pgtype.UUID
	Source                    string
	ExternalID                string
	Title                     string
	CompanyName               string
	Category                  string
	JobType                   string
	CandidateRequiredLocation string
	SalaryText                string
	ExternalUrl               string
	PublicationDate           pgtype.Timestamptz
	Description               string
	Status                    string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
